### ISSUE TITLE
use elm-color instead of custom color library?

### ISSUE THREAD

**Issue by seethroughtrees** [joakin/elm-canvas#1]
playing with this library, looks great so far.

question though.  would it not make more sense for type matching to use the native elm color instead of custom CanvasColor?

I might be missing the reason for not, just mentioning it in case.

This would allow for using other libraries for color like `elm-visualization` and color scales.

**Comment by joakin** [comment]
Nice! Glad you liked it!

I actually have the next major version on the works at

https://github.com/joakin/elm-canvas/tree/better-api-test-listsettings

Which uses that package and has a more helpful and elm like API.

I have to finish the docs and publish at some point, but that is already
fixed 👌

**Comment by seethroughtrees** [comment]
Oh that's great to hear.  I'll keep an eye out!  

Closing this as its already been addressed.
