### ISSUE TITLE
4.0.1 version - style background  issues

### ISSUE THREAD

**Issue by CatrielD** [joakin/elm-canvas#11]
Refactoring the [p5 examples](https://discourse.elm-lang.org/t/some-p5js-org-examples-in-elm/3781) to work with last version (4.0.1); found that the background color shrinks to a small height on the canvas.

Compare [color-hue from docs](https://ellie-app.com/5KQZKbKF5Rma1)[1] (canvas version 3.0.5)  with [color-hue refactored](https://ellie-app.com/85DG5fmyz8ca1) (canvas version 4.0.1)

the same happens with reactor.

[1] that doesn't compile on ellie, it seems that it ignores the version number and just uses the latest; but works just fine in a normal desktop setup. It compiles and the background color displays correctly.

**Comment by joakin** [comment]
It seems like the `elm-canvas` is not getting `display:block` and so it is not properly scaled so the css you apply to it looks strange.

From [Custom Element Best Practices](https://developers.google.com/web/fundamentals/web-components/best-practices):

> Custom elements are display: inline by default, so setting their width or height will have no effect. This often comes as a surprise to developers and may cause issues related to laying out the page. Unless you prefer an inline display, you should always set a default display value.


This works https://ellie-app.com/869YWKNhxtda1

And in the `elm-canvas` examples we use this snippet: https://github.com/joakin/elm-canvas/blob/dd61baab768343fe3dd2e364b7d61a9c1be45d16/public/index.css#L25-L29

If you can I'd be happy to take a PR that adds another note to [`toHtml`](https://github.com/joakin/elm-canvas/blob/dd61baab768343fe3dd2e364b7d61a9c1be45d16/src/Canvas.elm#L82) and [`toHtmlWith`](https://github.com/joakin/elm-canvas/blob/dd61baab768343fe3dd2e364b7d61a9c1be45d16/src/Canvas.elm#L113)  briefly explaining the default display for the element.

Hope this helps 👆!

**Comment by CatrielD** [comment]
Thanks for pointing me in the right direction! 

I've used 'display: [inline-flex](https://developer.mozilla.org/es/docs/Web/CSS/display)' for proper display. Using block, has a minor "glitch": an inferior black border.

I've created a [gitlab repo](https://gitlab.com/cato/elm-p5-examples) with the examples on the discourse page 

Ok, I'll make a PR.

**Comment by joakin** [comment]
Thanks CatrielD, I'll look at it soon 👍
