### ISSUE TITLE
arc function: anti clockwise doesn't work with startAngle < endAngle

### ISSUE THREAD

**Issue by CatrielD** [joakin/elm-canvas#16]
I should expect that we could maintain the angles and just reverse the orientation of the arcs. 

But trying to make a pie chart, I've found that only using startAngle > endAngle with clockwise = False works.
 
Using counter clockwise, [this one](https://ellie-app.com/87wS4PcJ3wya1) do not work as expected. [This](https://ellie-app.com/87x2N5SpgWMa1) other one, do work but it's rather confusing that startAngle must be greater than endAngle.  Besides it's putting every arc next to the other in a clockwise manner. I except for the first one to be red in the top right quadrant, green on the top-left one and blue in the lower one.

It's like the angles always are clockwise and fall in the same way no matter if clockwise it's true or false, but only it fills well if the direction of the fill it's in accordance with clock direction (startAngle > endAngle for clockwise, the other way around for anti-clockwise) very confusing.

**Comment by joakin** [comment]
I can see how it could be confusing.

If you start at 0, and go ccw, you go around the whole circle until the 90 mark https://ellie-app.com/88GKgcTk6Wwa1

You can see how the 0 degrees mark is at the right, and 90 degrees is at the bottom: https://ellie-app.com/88GHFrPwmxDa1

Seems like not knowing the coordinate system of the arc hurts the usability of the function.

Thoughts about how to improve this? More documentation on the arc function could be an easy way. Rethinking the clockwise/anticlockwise setting and the coordinates of angles of the arc is another one.

**Comment by joakin** [comment]
I've published 4.1.0 with the improved docs that you PRd and some of my additions, see here:

https://package.elm-lang.org/packages/joakin/elm-canvas/latest/Canvas#arc

Let me know if that works for you :D
