### ISSUE TITLE
Unexpected scene

### ISSUE THREAD

**Issue by linsyking** [joakin/elm-canvas#37]
In your example `Textures.elm` line 147, If you delete `rect ( 0, 0 ) w h`, then everything becomes strange.
It seems that you have to add a "curtain" behind everything, is it normal?
What's the principle of it?

**Comment by joakin** [comment]
The Dom canvas is like a paper canvas, it is never automatically cleared, so if you want to do animation you have to clear the canvas somehow each frame.

With the library you just make a big rect and cover the whole thing up to start fresh this frame.
